# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Auto install k8s using sealos'
description: 'Auto install k8s using sealos'
author: 'cuisongliu'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  type:
    description: 'Type of sealos cmd'
    required: true
    default: 'install'

  sealosVersion:
    description: 'sealos release version'
    default: "4.1.3"

  sealctl:
    description: 'sealctl for sealos'
    default: "false"

  working-directory:
    description: "Directory to run `sealos build` from, if not project root"
    default: "."

#outputs:
#  result:
#    description: action result

runs:
  using: "composite"
  steps:
    - run: |
        sudo mkdir -p /tmp/.sealos-action
        sudo cp -rf /home/runner/work/_actions/labring/sealos-action/v0.0.2/.sealos-action* /tmp/.sealos-action/
        bash /tmp/.sealos-action/.sealos-action.sh
      shell: bash
      id: default
      env:
        cmd: ${{ inputs.type }}
        install_sealctl: ${{ inputs.sealctl }}
        sealos_version: ${{ inputs.sealosVersion }}
        action_directory: .sealos-action
      working-directory: ${{ inputs.working-directory }}
